In [3]:
import numpy as np

In [4]:
x = np.arange(12).reshape(2,6)

In [5]:
np.empty_like(x)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [6]:
n, m = x.shape
v = x[0, 0]
for i in range(n):
    for j in range(m):
        if x[i, j]>v:
            v = x[i, j]

v

11

In [7]:
y = np.empty_like(x)
for i in range(n):
    for j in range(m):
        y[i, j] = x[i, j] - v

y

array([[-11, -10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1,   0]])

In [8]:
x - x.max()

array([[-11, -10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1,   0]])

In [9]:
def exercise22_loop(x):
    n, m = x.shape
    v = x[0, 0]
    for i in range(n):
        for j in range(m):
            if x[i, j]>v:
                v = x[i, j]

    y = np.empty_like(x)
    for i in range(n):
        for j in range(m):
            y[i, j] = x[i, j] - v

    return y

In [10]:
def exercise22_vectorized(x):
    return x - x.max()

In [11]:
exercise22_loop(x)

array([[-11, -10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1,   0]])

In [12]:
exercise22_vectorized(x)

array([[-11, -10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1,   0]])

In [13]:
assert 'exercise22_loop' in globals(), "You forgot to run the code cell with the loop-based code!"
assert 'exercise22_vectorized' in globals(), "You forgot to run the code cell with your answer!"
for i in range(10):
    x = np.random.randint(100, size=(5, 3))
    y = exercise22_vectorized(x)
    y_correct = exercise22_loop(x)
    assert isinstance(y, np.ndarray), "You didn't return an ndarray object!"
    assert y.shape == x.shape, "You returned an ndarray but of the wrong shape!"
    assert y.dtype == x.dtype, "You returned an ndarray but of the wrong dtype!"
    assert np.array_equal(y, y_correct), "Wrong result!\nx:\n%s\nexpected:\n%s\nreturned:\n%s" % (x, y_correct, y)
print("Correct!")

# import timeit
# x = np.random.randint(1000, size=(200, 200))
# loop_time = timeit.timeit('exercise22_loop(x)',      setup="from _main_ import exercise22_loop, x", number=10)
# vec_time = timeit.timeit('exercise22_vectorized(x)', setup="from _main_ import exercise22_vectorized, x", number=10)
# print("You vectorized code ran %.1fx faster than the original code on a 200x200 matrix" % (loop_time/vec_time))

Correct!


ModuleNotFoundError: No module named '_main_'

In [14]:
x = np.random.randint(1000, size=(200, 200))

In [15]:
%%timeit

exercise22_loop(x)

22.8 ms ± 670 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
%%timeit
exercise22_vectorized(x)

68.5 µs ± 516 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
